### ISSUE TITLE
не стартует backend (No repository for "UserEntity" was found.)

### ISSUE THREAD

**Issue by odmin4eg** [mogilevtsevdmitry/nestjs-postgresql-typeorm-docker#1]
Привет, запуск проекта происходит со сбоем.

```$ yarn start
yarn run v1.22.5
warning ../package.json: No license field
$ nest start
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [NestFactory] Starting Nest application...
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [InstanceLoader] AppModule dependencies initialized +31ms
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +157ms
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [InstanceLoader] GraphQLModule dependencies initialized +1ms
[Nest] 668709  - 18.04.2022, 15:21:57     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +10ms
[Nest] 668709  - 18.04.2022, 15:21:57   **ERROR [ExceptionHandler] No repository for "UserEntity" was found. Looks like this entity is not registered in current "default" connection?
RepositoryNotFoundError: No repository for "UserEntity" was found. Looks like this entity is not registered in current "default" connection?**
    at RepositoryNotFoundError.TypeORMError [as constructor] (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/src/error/TypeORMError.ts:7:9)
    at new RepositoryNotFoundError (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/src/error/RepositoryNotFoundError.ts:10:9)
    at MongoEntityManager.EntityManager.getRepository (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/src/entity-manager/EntityManager.ts:987:19)
    at Connection.getMongoRepository (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/src/connection/Connection.ts:358:29)
    at InstanceWrapper.useFactory [as metatype] (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/node_modules/@nestjs/typeorm/dist/typeorm.providers.js:16:30)
    at Injector.instantiateClass (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/node_modules/@nestjs/core/injector/injector.js:304:55)
    at callback (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/node_modules/@nestjs/core/injector/injector.js:48:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Injector.resolveConstructorParams (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/node_modules/@nestjs/core/injector/injector.js:124:24)
    at Injector.loadInstance (/home/developer/code/angular-nestjs-postgresql-typeorm-graphql-docker/backend/node_modules/@nestjs/core/injector/injector.js:52:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mogilevtsevdmitry** [comment]
Сегодня столкнулся с той же проблемой, пока отложил, это что-то на стороне TypeORM видимо
